#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: carvelpkg-provider
spec:
  params:
    - name: serviceAccount
      default: default

  imagePath: .status.outputs.image-ref

  ytt: |
    #@ load("@ytt:data", "data")

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    #@ def param(key):
    #@   if not key in data.values.params:
    #@     return None
    #@   end
    #@   return data.values.params[key]
    #@ end

    #@ def image():
    #@   return "/".join([
    #@    data.values.params.registry.server,
    #@    data.values.params.registry.repository,
    #@    "-".join([
    #@      data.values.workload.metadata.name,
    #@      data.values.workload.metadata.namespace,
    #@    ])
    #@   ])
    #@ end

    #@ def ca_cert_data():
    #@   if "ca_cert_data" not in param("registry"):
    #@     return ""
    #@   end
    #@
    #@   return param("registry")["ca_cert_data"]
    #@ end

    ---
    apiVersion: carto.run/v1alpha1
    kind: Runnable
    metadata:
      name: #@ data.values.workload.metadata.name + "-pkg-build"
      labels: #@ merge_labels({ "app.kubernetes.io/component": "build" })
    spec:
      #@ if/end hasattr(data.values.workload.spec, "serviceAccountName"):
      serviceAccountName: #@ data.values.workload.spec.serviceAccountName

      runTemplateRef:
        name: carvelpkg-runtemplate

      inputs:
        serviceAccount: #@ data.values.params.serviceAccount
        params:
          - name: workload_name
            value: #@ data.values.workload.metadata.name
          - name: image
            value: #@ image()
          - name: ca_cert_data
            value: #@ ca_cert_data()


